### ISSUE TITLE
CI doesn't work from forked repos

### ISSUE THREAD

**Issue by Incognito** [freight-hub/TypedEnv#49]
We need to enable this on CI, but we'll also need to lock-down the deployment secret to prevent execution of third-party code getting access to our delivery pipeline (especially, `NPM_TOKEN`).

We have to do this part to prevent someone from making a PR against our repo that emails the attacker with our credentials.

**Comment by matang-dave** [comment]
closing in favour of  https://github.com/freight-hub/TypedEnv/pull/211
